apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: sonar-space
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi # Ajusta el tamaño según tus necesidades